config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  namespace :api do
    resources :people, only: %i[create]
    resources :doctors, only: %i[create]
  end

  localized do
    namespace :accounts do
      resource :sessions, only: %i[new create destroy]
      resources :registrations, only: %i[index new create]
      resources :passwords, only: %i[index edit update] do
        collection do
          get :remember
        end
      end
    end

    namespace :patients do
      resources :permissions, only: %i[index new create destroy] do
        collection do
          get :search_doctor
        end
      end
      resources :my_medical_records, only: %i[index show] do
        collection do
          get :search_result
        end
      end
    end

    namespace :doctors do
      resources :medical_records, only: %i[index new create] do
        collection do
          get :patient_records
        end
      end
      resources :permissions, only: %i[destroy]
      resources :my_appointments, only: %i[index show] do
        collection do
          get :search_result
        end
      end
    end
  end
end

app/models/doctor.rb
class Doctor < ApplicationRecord
  belongs_to :person
  has_many :attendances
  has_many :permissions

  validates_presence_of :crm
end

app/controllers/api/doctors_controller.rb
module Api
  class DoctorsController < Api::BaseController
    def create
      @pessoa = Pessoa.find_by!(cns: doctor_params[:cns])

      if @pessoa.medico.blank?
        create_medico
      else
        render json: Hash[errors: 'Esta pessoa já é um médico'],
               status: :unprocessable_entity
      end
    end

    private

    def doctor_params
      params.require(:medico).permit(
        :crm,
        :cns
      )
    end

    def create_medico
      @medico = @pessoa.build_medico(crm: doctor_params[:crm])

      if @medico.save
        render json: @medico, status: :created
      else
        render json: Hash[errors: @medico.errors], status: :unprocessable_entity
      end
    end
  end
end

app/controllers/doctors/base_controller.rb
module Doctors
  class BaseController < AuthenticatedController
    protected

    def authenticate_pessoa!
      super
      return if current_pessoa.medico.present?
      flash[:alert] = 'Você não pode acessar a página solicitada'
      redirect_to root_path
    end
  end
end

app/controllers/doctors/medical_records_controller.rb
module Doctors
  class MedicalRecordsController < Doctors::BaseController
    before_action :load_permission!, except: %i[index]
    rescue_from 'MedicalRecords::AttendanceNotAllowed',
                with: :attendance_not_allowed_handler

    def index
      @permissoes = current_pessoa.medico.permissoes.
                    includes(:pessoa).
                    joins(:pessoa).
                    actived
    end

    def patient_records
      @atendimentos = @permissao.pessoa.atendimentos.
                      joins(medico: :pessoa).
                      order(data_atendimento: :desc)
    end

    def new
      @atendimento = Atendimento.new
    end

    def create
      @atendimento = create_medical_records

      if @atendimento.persisted?
        flash[:success] = 'Atendimento registrado com sucesso'
        redirect_to doctors_my_appointment_path(
          @atendimento,
          back_to: doctors_my_appointments_path
        )
      else
        render :new
      end
    end

    private

    def load_permission!
      return if permissao.present?
      flash[:error] = 'Você não possui permissão para acessar o prontuário.'
      redirect_to action: :index
    end

    def attendance_not_allowed_handler(exception)
      flash[:error] = exception.message
      redirect_to action: :index
    end

    def permissao
      @permissao ||= Permissao.actived.find_by(
        id: params[:permissao_id],
        medico: current_pessoa.medico
      )
    end

    def create_medical_records
      MedicalRecords::Create.new(
        permission: @permissao,
        doctor: current_pessoa.medico,
        record: atendimento_params
      ).call
    end

    def atendimento_params
      params.require(:atendimento).permit(
        :sintomas,
        :diagnosticos,
        :prescricao_medicamentos,
        :prescricao_procedimentos
      )
    end
  end
end

app/controllers/doctors/my_appointments_controller.rb
module Doctors
  class MyAppointmentsController < Doctors::BaseController
    def index
      @search = Doctors::MyAppointments::SearchForm.new
    end

    def search_result
      @search = Doctors::MyAppointments::SearchForm.new(search_params)

      if @search.valid?
        @atendimentos = search_atendimentos
      else
        render :index unless @search.valid?
      end
    end

    def show
      @atendimento = Atendimento.joins(:pessoa).find_by!(
        id: params[:id],
        medico: current_pessoa.medico
      )
    end

    private

    def search_params
      params.require(:doctors_my_appointments_search_form).permit(
        :initial_date,
        :final_date,
        :patient_name,
        :query_text
      )
    end

    def search_atendimentos
      Atendimento.search(
        initial_date: @search.initial_date,
        final_date: @search.final_date,
        params: query_params
      ).records.joins(:pessoa)
    end

    def query_params
      query_params = Hash[medico_id: current_pessoa.medico.id]

      if @search.query_text.present?
        query_params[:query_text] = @search.query_text
      end

      if @search.patient_name.present?
        query_params[:pessoa_nome] = @search.patient_name
      end

      query_params
    end
  end
end

app/controllers/doctors/permissions_controller.rb
module Doctors
  class PermissionsController < Doctors::BaseController
    def destroy
      Permissions::Refuse.new(
        doctor: current_pessoa.medico,
        permission_id: params[:id].try(:to_i)
      ).call

      flash[:success] = 'Autorização recusada com sucesso'
      redirect_to doctors_medical_records_path
    end
  end
end

app/views/doctors/medical_records/_patient_info.html.slim
div.pb-2
  = render 'doctors/shared/patient_info', pessoa: permissao.pessoa
  em
    | Esta autorização é válida até:
    strong<> = l(permissao.data_limite, format: :custom)

app/views/doctors/medical_records/index.html.slim
.container
  section#title-area
    h1 Novo Atendimento
    em
      | Abaixo estão as autorizações que você recebeu de pacientes para acessar
      | seus prontuários. Você pode recusar a autorização se achar necessário.
  hr

  section#permissions-area
    - if @permissoes.present?
      - @permissoes.each do |permissao|
        = render 'patient_info', permissao: permissao
        .text-center.pb-2
          = link_to 'Acessar Prontuário', patient_records_doctors_medical_records_path(permissao_id: permissao), class: 'btn btn-primary'
        .text-center
          = link_to 'Recusar Autorização', doctors_permission_path(permissao), class: 'btn btn-danger', method: :delete, data: { confirm: "Tem certeza que deseja recusar a autorização do paciente #{permissao.pessoa.nome_completo}?" }
        hr
    - else
      p.text-center.attention
        | No momento você não possui autorizações ativas.

app/views/doctors/medical_records/new.html.slim
.container
  section#title-area
    h1 Novo Atendimento
  hr

  section#patient-area
    h2
      | Dados do Paciente
    = render 'patient_info', permissao: @permissao
  hr

  section#form-area
    h2
      | Dados do Atendimento

    = simple_form_for(@atendimento, url: doctors_medical_records_path(permissao_id: @permissao.id), method: :post) do |f|
      = f.input :sintomas, input_html: { rows: 10 }
      = f.input :diagnosticos, input_html: { rows: 10 }
      = f.input :prescricao_medicamentos, input_html: { rows: 10 }
      = f.input :prescricao_procedimentos, input_html: { rows: 10 }
      .text-center
        p.required-hint
          | Os campos marcados com * precisam ser preenchidos
        = f.submit value: 'Gravar Atendimento', class: 'btn btn-primary', data: { disable_with: '...', confirm: "Você não poderá alterar este registro após gravá-lo.\nTem certeza que seja gravar o atendimento agora?" }

app/views/doctors/medical_records/patient_records.html.slim
.container
  section#title-area
    h1 Novo Atendimento
  hr

  section#patient-area
    h2
      | Dados do Paciente
    = render 'patient_info', permissao: @permissao

  section#actions-area
    .row
      .col-12.text-center
        = link_to 'Voltar', doctors_medical_records_path, class: 'btn btn-secondary'
        = link_to 'Novo Atendimento', new_doctors_medical_record_path(permissao_id: @permissao.id), class: 'btn btn-primary ml-20'

  hr

  section#medical-records-area
    h2
      | Prontuário
    - if @atendimentos.present?
      - @atendimentos.each do |atendimento|
        .mb-2
          .medical-records.col-12
            dl.title.row.mb-2
              dt.col-3
                | Data:
              dd.col-9
                = l(atendimento.data_atendimento, format: :long)
              dt.col-3
                | Médico:
              dd.col-9
                = atendimento.medico.pessoa.nome_completo
            dl.records.row
              dt.col-12
                | Sintomas Apresentados:
              dd.col-12
                = simple_format(atendimento.sintomas)
              dt.col-12
                | Diagnóstico:
              dd.col-12
                = simple_format(atendimento.diagnosticos)
              dt.col-12
                | Prescrição de Medicamentos:
              dd.col-12
                = simple_format(atendimento.prescricao_medicamentos)
              dt.col-12
                | Prescrição de Procedimentos:
              dd.col-12
                = simple_format(atendimento.prescricao_procedimentos)
    - else
      p.text-center.attention
        | O paciente não possui registros médicos em seu prontuário.

  - if @atendimentos.count > 1
    hr

    section#actions-footer-area
      .row
        .col-12.text-center
          = link_to 'Voltar', doctors_medical_records_path, class: 'btn btn-secondary'
          = link_to 'Novo Atendimento', new_doctors_medical_record_path(permissao_id: @permissao.id), class: 'btn btn-primary ml-20'