config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  namespace :api do
    resources :people, only: %i[create]
    resources :doctors, only: %i[create]
  end

  localized do
    namespace :accounts do
      resource :sessions, only: %i[new create destroy]
      resources :registrations, only: %i[index new create]
      resources :passwords, only: %i[index edit update] do
        collection do
          get :remember
        end
      end
    end

    namespace :patients do
      resources :permissions, only: %i[index new create destroy] do
        collection do
          get :search_doctor
        end
      end
      resources :my_medical_records, only: %i[index show] do
        collection do
          get :search_result
        end
      end
    end

    namespace :doctors do
      resources :medical_records, only: %i[index new create] do
        collection do
          get :patient_records
        end
      end
      resources :permissions, only: %i[destroy]
      resources :my_appointments, only: %i[index show] do
        collection do
          get :search_result
        end
      end
    end
  end
end

app/models/permission.rb
class Permission < ApplicationRecord
  belongs_to :attendance
  belongs_to :doctor
  belongs_to :person

  validates_presence_of :date
end

app/controllers/doctors/permissions_controller.rb
module Doctors
  class PermissionsController < Doctors::BaseController
    def destroy
      Permissions::Refuse.new(
        doctor: current_pessoa.medico,
        permission_id: params[:id].try(:to_i)
      ).call

      flash[:success] = 'Autorização recusada com sucesso'
      redirect_to doctors_medical_records_path
    end
  end
end

app/controllers/patients/my_medical_records_controller.rb
module Patients
  class MyMedicalRecordsController < AuthenticatedController
    def index
      @search = Patients::MyMedicalRecords::SearchForm.new
    end

    def search_result
      @search = Patients::MyMedicalRecords::SearchForm.new(search_params)

      if @search.valid?
        @atendimentos = search_atendimentos
      else
        render :index unless @search.valid?
      end
    end

    def show
      @atendimento = Atendimento.joins(:pessoa, medico: :pessoa).find_by!(
        id: params[:id],
        pessoa: current_pessoa
      )
    end

    private

    def search_params
      params.require(:patients_my_medical_records_search_form).permit(
        :initial_date,
        :final_date,
        :doctor_name,
        :query_text
      )
    end

    def search_atendimentos
      Atendimento.search(
        initial_date: @search.initial_date,
        final_date: @search.final_date,
        params: query_params
      ).records.joins(:pessoa, medico: :pessoa)
    end

    def query_params
      query_params = Hash[pessoa_id: current_pessoa.id]

      if @search.query_text.present?
        query_params[:query_text] = @search.query_text
      end

      if @search.doctor_name.present?
        query_params[:medico_nome] = @search.doctor_name
      end

      query_params
    end
  end
end

app/controllers/patients/permissions_controller.rb
module Patients
  class PermissionsController < AuthenticatedController
    rescue_from 'Permissions::AlreadyExistsError', with: :error_handler
    rescue_from 'Permissions::SelfPermissionNotAllowed', with: :error_handler

    def index
      @permissoes = current_pessoa.permissoes.
                    includes(medico: :pessoa).
                    joins(medico: :pessoa).
                    granted.
                    pending_appointment.
                    current
    end

    def search_doctor; end

    def new
      @medico = Medico.joins(:pessoa).find_by!(crm: params[:crm])
      @permissao = Permissao.new(medico: @medico)
    rescue ActiveRecord::RecordNotFound
      flash[:error] = "O CRM #{params[:crm]} não esta cadastrado no SPE"
      redirect_to action: :search_doctor
    end

    def create
      @medico = Medico.find(permissao_params[:medico_id])
      @permissao = create_permissao

      if @permissao.persisted?
        flash[:success] = 'O médico recebeu a autorização com sucesso'
        redirect_to action: :index
      else
        render :new
      end
    end

    def destroy
      Permissions::Revoke.new(
        patient: current_pessoa,
        permission_id: params[:id].try(:to_i)
      ).call

      flash[:success] = 'Autorização revogada com sucesso'
      redirect_to action: :index
    end

    private

    def create_permissao
      Permissions::Create.new(
        patient: current_pessoa,
        doctor: @medico,
        deadline: permissao_params[:data_limite]
      ).call
    end

    def permissao_params
      params.require(:permissao).permit(:data_limite, :medico_id)
    end

    def error_handler(exception)
      flash[:error] = exception.message
      redirect_to action: :search_doctor
    end
  end
end

app/views/patients/permissions/index.html.slim
.container
  section#title-area
    h1 Médicos Autorizados
  hr

  section#permissions-area
    - if @permissoes.present?
      - @permissoes.each do |permissao|
        div.pb-2
          dl.row
            dt.col-2
              | CRM
            dd.col-10
              = permissao.medico.crm
            dt.col-2
              | Nome
            dd.col-10
              = permissao.medico.pessoa.nome_completo
          em
            - if permissao.refused?
              | Esta autorização era válida até:
            - else
              | Esta autorização é válida até:
            strong<> = l(permissao.data_limite, format: :custom)
        - if permissao.refused?
          p.text-center.attention
            | O médico não aceitou esta autorização.
        .text-center
          = link_to 'Revogar Autorização', patients_permission_path(permissao), class: 'btn btn-danger', method: :delete, data: { confirm: "Tem certeza que deseja revogar a autorização ao médico #{permissao.medico.pessoa.nome_completo}?" }
        hr
    - else
      p.text-center
        | No momento você não possui autorizações ativas. Para autorizar um médico clique no botão abaixo:
      .text-center
        = link_to 'Autorizar Médico', search_doctor_patients_permissions_path, class: 'btn btn-primary'

app/views/patients/permissions/new.html.slim
.container
  section#title-area
    h1 Autorizar Médico
  hr
  section#doctor-info
    h2 Dados do Médico
    dl.row
      dt.col-2
        | CRM
      dd.col-10
        = @medico.crm
      dt.col-2
        | Nome
      dd.col-10
        = @medico.pessoa.nome_completo
  hr
  section#permission-info
    h2 Dados da Permissão
    em
      | Informe até quando você deseja conceder autorização ao médico para acessar seu prontuário.
      | A autorização será válida até a data e hora indicada, podendo ser revogada a qualquer momento.
    = simple_form_for(@permissao, url: patients_permissions_path, method: :post) do |f|
      = f.input :medico_id, as: :hidden
      = f.input :data_limite, as: :string, input_html: { type: 'datetime-local' }, label: 'Data para término da autorização', placeholder: 'Escolha uma data e hora'
      .text-center
        p.required-hint
          | O campo marcado com * precisa ser preenchido
        = f.submit value: 'Autorizar Médico', class: 'btn btn-primary', data: { disable_with: '...' }

app/views/patients/permissions/search_doctor.html.slim
.container
  section#title-area
    h1 Autorizar Médico
    hr
    em Informe o CRM do médico que você deseja autorizar acesso ao seu prontuário.
  section#form-area
    = form_tag(new_patients_permission_path, method: :get)
      .form-group.crm.required
        label.control-label.crm.required[for="crm"]
          abbr[title="required"]
            | *
          |  CRM do Médico
        input#crm.form-control.string.crm.required[required="required" aria-required="true" placeholder="Número do CRM do Médico" type="text" name="crm"]
      .text-center
        p.required-hint
          | O campo marcado com * precisa ser preenchido
        input.btn.btn-primary[type="submit" name="commit" value="Pesquisar" data-disable-with="..."]