config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  namespace :api do
    resources :people, only: %i[create]
    resources :doctors, only: %i[create]
  end

  localized do
    namespace :accounts do
      resource :sessions, only: %i[new create destroy]
      resources :registrations, only: %i[index new create]
      resources :passwords, only: %i[index edit update] do
        collection do
          get :remember
        end
      end
    end

    namespace :patients do
      resources :permissions, only: %i[index new create destroy] do
        collection do
          get :search_doctor
        end
      end
      resources :my_medical_records, only: %i[index show] do
        collection do
          get :search_result
        end
      end
    end

    namespace :doctors do
      resources :medical_records, only: %i[index new create] do
        collection do
          get :patient_records
        end
      end
      resources :permissions, only: %i[destroy]
      resources :my_appointments, only: %i[index show] do
        collection do
          get :search_result
        end
      end
    end
  end
end

app/controllers/patients/my_medical_records_controller.rb
module Patients
  class MyMedicalRecordsController < AuthenticatedController
    def index
      @search = Patients::MyMedicalRecords::SearchForm.new
    end

    def search_result
      @search = Patients::MyMedicalRecords::SearchForm.new(search_params)

      if @search.valid?
        @atendimentos = search_atendimentos
      else
        render :index unless @search.valid?
      end
    end

    def show
      @atendimento = Atendimento.joins(:pessoa, medico: :pessoa).find_by!(
        id: params[:id],
        pessoa: current_pessoa
      )
    end

    private

    def search_params
      params.require(:patients_my_medical_records_search_form).permit(
        :initial_date,
        :final_date,
        :doctor_name,
        :query_text
      )
    end

    def search_atendimentos
      Atendimento.search(
        initial_date: @search.initial_date,
        final_date: @search.final_date,
        params: query_params
      ).records.joins(:pessoa, medico: :pessoa)
    end

    def query_params
      query_params = Hash[pessoa_id: current_pessoa.id]

      if @search.query_text.present?
        query_params[:query_text] = @search.query_text
      end

      if @search.doctor_name.present?
        query_params[:medico_nome] = @search.doctor_name
      end

      query_params
    end
  end
end

app/controllers/patients/permissions_controller.rb
module Patients
  class PermissionsController < AuthenticatedController
    rescue_from 'Permissions::AlreadyExistsError', with: :error_handler
    rescue_from 'Permissions::SelfPermissionNotAllowed', with: :error_handler

    def index
      @permissoes = current_pessoa.permissoes.
                    includes(medico: :pessoa).
                    joins(medico: :pessoa).
                    granted.
                    pending_appointment.
                    current
    end

    def search_doctor; end

    def new
      @medico = Medico.joins(:pessoa).find_by!(crm: params[:crm])
      @permissao = Permissao.new(medico: @medico)
    rescue ActiveRecord::RecordNotFound
      flash[:error] = "O CRM #{params[:crm]} não esta cadastrado no SPE"
      redirect_to action: :search_doctor
    end

    def create
      @medico = Medico.find(permissao_params[:medico_id])
      @permissao = create_permissao

      if @permissao.persisted?
        flash[:success] = 'O médico recebeu a autorização com sucesso'
        redirect_to action: :index
      else
        render :new
      end
    end

    def destroy
      Permissions::Revoke.new(
        patient: current_pessoa,
        permission_id: params[:id].try(:to_i)
      ).call

      flash[:success] = 'Autorização revogada com sucesso'
      redirect_to action: :index
    end

    private

    def create_permissao
      Permissions::Create.new(
        patient: current_pessoa,
        doctor: @medico,
        deadline: permissao_params[:data_limite]
      ).call
    end

    def permissao_params
      params.require(:permissao).permit(:data_limite, :medico_id)
    end

    def error_handler(exception)
      flash[:error] = exception.message
      redirect_to action: :search_doctor
    end
  end
end

app/views/patients/my_medical_records/index.html.slim
.container
  section#title-area
    h1 Meu Prontuário
    em
      | Pesquise seus atendimentos por período. Informe o nome do médico se desejar
      | encontrar os atendimentos realizado por um médico específico.
  hr
    = simple_form_for(@search, url: search_result_patients_my_medical_records_path, method: :get) do |f|
      = f.input :initial_date, input_html: { type: 'datetime-local' }, placeholder: 'Data inicial para pesquisa'
      = f.input :final_date, input_html: { type: 'datetime-local' }, placeholder: 'Data final para pesquisa'
      = f.input :doctor_name, placeholder: 'Nome do médico'
      = f.input :query_text, placeholder: 'Palavras-chave do atendinento', hint: 'Pesquise sintomas, diagnósticos, medicamentos e procedimentos'
      .text-center
        p.required-hint
          | Os campos marcados com * precisam ser preenchidos
        = f.submit value: 'Pesquisar', class: 'btn btn-primary', data: { disable_with: '...' }

app/views/patients/my_medical_records/search_result.html.slim
.container
  section#title-area
    h1 Meu Prontuário
  hr

  section#search-params-area
    h2 Critérios de Pesquisa
    div.pb-2
      dl.row
        dt.col-4
          | Data Inicial
        dd.col-8
          = l(@search.initial_date, format: :date_time)
        dt.col-4
          | Data Final
        dd.col-8
          = l(@search.final_date, format: :date_time)
        - if @search.doctor_name.present?
          dt.col-4
            | Médico
          dd.col-8
            = @search.doctor_name
        - if @search.query_text.present?
          dt.col-4.query-text-title
            | Palavras-Chave
          dd.col-8
            = @search.query_text
  hr

  section#appointments-area
    h2 Atendimentos Encontrados (#{@atendimentos.count}):

    - if @atendimentos.present?
      table.table.table-striped
        thead.thead-default
          tr
            th.date-column Data
            th Médico
            th.action-column
        tbody
          - @atendimentos.each do |atendimento|
            tr
              td
                = link_to l(atendimento.data_atendimento.to_date), patients_my_medical_record_path(atendimento)
              td
                = link_to atendimento.medico.pessoa.nome_completo, patients_my_medical_record_path(atendimento)
              td
                = link_to 'Ver', patients_my_medical_record_path(atendimento), class: 'btn btn-warning btn-sm'
    - else
      p.text-center.attention
        | Nenhum atendimento foi encontrado com os critérios de pesquisa informados.
  hr

  section#actions-buttons-area
    .text-center
      = link_to 'Nova Pesquisa', patients_my_medical_records_path, class: 'btn btn-secondary'

app/views/patients/my_medical_records/show.html.slim
.container
  section#title-area
    h1 Meu Prontuário
  hr

  section#patient-area
    h2
      | Dados do Médico
    dl.row
      dt.col-2
        | CRM
      dd.col-10
        = @atendimento.medico.crm
      dt.col-2
        | Nome
      dd.col-10
        = @atendimento.medico.pessoa.nome_completo

  hr

  section#appointment-area
    h2
      | Detalhes do Atendimento
    .mb-2
      .medical-records.col-12
        dl.title.row.pt-2.mb-2
          dt.col-2
            | Data:
          dd.col-10
            = l(@atendimento.data_atendimento, format: :long)
        dl.records.row
          dt.col-12
            | Sintomas Apresentados:
          dd.col-12
            = simple_format(@atendimento.sintomas)
          dt.col-12
            | Diagnóstico:
          dd.col-12
            = simple_format(@atendimento.diagnosticos)
          dt.col-12
            | Prescrição de Medicamentos:
          dd.col-12
            = simple_format(@atendimento.prescricao_medicamentos)
          dt.col-12
            | Prescrição de Procedimentos:
          dd.col-12
            = simple_format(@atendimento.prescricao_procedimentos)
  hr

  section#actions-area
    .row
      .col-12.text-center
        = link_to 'Voltar Para a Pesquisa', :back, class: 'btn btn-secondary'