config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  namespace :api do
    resources :people, only: %i[create]
    resources :doctors, only: %i[create]
  end

  localized do
    namespace :accounts do
      resource :sessions, only: %i[new create destroy]
      resources :registrations, only: %i[index new create]
      resources :passwords, only: %i[index edit update] do
        collection do
          get :remember
        end
      end
    end

    namespace :patients do
      resources :permissions, only: %i[index new create destroy] do
        collection do
          get :search_doctor
        end
      end
      resources :my_medical_records, only: %i[index show] do
        collection do
          get :search_result
        end
      end
    end

    namespace :doctors do
      resources :medical_records, only: %i[index new create] do
        collection do
          get :patient_records
        end
      end
      resources :permissions, only: %i[destroy]
      resources :my_appointments, only: %i[index show] do
        collection do
          get :search_result
        end
      end
    end
  end
end

app/views/layouts/application.html.slim
doctype html
html[lang="pt-BR"]
  head
    title
      | Bem-vindo | Sistema de Prontuário Eletrônico - SPE
    meta[name="description" content="Seja bem-vindo ao portal do Sistema de Prontuário Eletrônico."]
    meta[charset="utf-8"]
    meta[http-equiv="Content-Type" content="text/html; charset=utf-8"]
    meta[name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"]
    meta[name="robots" content="noindex, nofollow"]
    = csrf_meta_tags
    = stylesheet_link_tag 'application', media: 'all'
    = yield(:stylesheet)
  body
    main
      nav.navbar.collapse.navbar-dark.bg-dark.container
        a.navbar-brand[href="/"]
          | SPE
        button.navbar-toggler[type="button" data-toggle="collapse" data-target="#navbarsDefault" aria-controls="navbarsDefault" aria-expanded="false" aria-label="Toggle navigation"]
          span.navbar-toggler-icon
        #navbarsDefault.collapse.navbar-collapse
          ul.navbar-nav.ml-auto.text-right
            - if pessoa_signed_in?
              li.nav-item.user-name.mt-3
                small Usuário:
                |  #{current_pessoa.nome_completo}
              - if medico_signed_in?
                li.nav-item.title-item.mt-3
                  | Para Médicos
                li.nav-item
                  = link_to 'Novo Atendimento', doctors_medical_records_path, class: 'nav-link'
                li.nav-item
                  = link_to 'Meus Atendimentos', doctors_my_appointments_path, class: 'nav-link'
              li.nav-item.title-item.mt-3
                | Para Pacientes
              li.nav-item
                = link_to 'Meu Prontuário', patients_my_medical_records_path, class: 'nav-link'
              li.nav-item
                = link_to 'Autorizar Médico', search_doctor_patients_permissions_path, class: 'nav-link'
              li.nav-item
                = link_to 'Médicos Autorizados', patients_permissions_path, class: 'nav-link'
              li.nav-item.mt-3
                = link_to 'Sair', accounts_sessions_path, method: :delete, class: 'nav-link'
            - else
              li.nav-item
                = link_to 'Login', new_accounts_sessions_path, class: 'nav-link'
              li.nav-item
                = link_to 'Criar Conta de Acesso', accounts_registrations_path, class: 'nav-link'

      - flash.each do |key, value|
        div[class="#{flash_class(key)} alert-dismissible fade show" role="alert"]
          = value
          button.close[type="button" data-dismiss="alert" aria-label="Close"]
            span[aria-hidden="true"]
              | ×
      = yield
      footer.container
        hr
        p
          | © Sistema de Prontuário Eletrônico - SPE
          = Date.today.year
    = javascript_include_tag 'application'
    = yield(:javascript)